### ISSUE TITLE
open kmbmpdc.app - LSOpenURLsWithRole() failed with error

### ISSUE THREAD

**Issue by majun** [arttuperala/kmbmpdc#2]
I have donwloaded last version [v1.0.0](https://github.com/arttuperala/kmbmpdc/releases/download/v1.0.0/kmbmpdc.tar.gz), extracted, copied to ~/Applications, run and got error...

```
$ open kmbmpdc.app
LSOpenURLsWithRole() failed with error -10810 for the file ~/Applications/kmbmpdc.app.
```

Any idea for this issue?

Thanks a lot.
Martin

**Comment by arttuperala** [comment]
1. What operating system are you running the application on?
2. Is Gatekeeper enabled?
3. Does executing the `kmbmpdc.app/Contents/MacOS/kmbmpdc` binary file do anything?

**Comment by majun** [comment]
I'm sorry... here are details:

1) Sierra 10.12.2

2) Gatekeeper: "App Store and identified developers" - has to be "Anywhere"? If yes I found this http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

3) output:
```
$ kmbmpdc.app/Contents/MacOS/kmbmpdc
dyld: Library not loaded: /usr/local/lib/libmpdclient.2.dylib
  Referenced from: /Users/jungerm/Applications/kmbmpdc.app/Contents/MacOS/kmbmpdc
  Reason: image not found
Abort trap: 6
```

**Comment by majun** [comment]
ad 3. I installed *libmpdclient* and it's working! 👍 
```
$ brew install libmpdclient
$ open kmbmpdc.app
```

**Comment by arttuperala** [comment]
Yeah, seems like I've forgotten to embed the libmpdclient.2.dylib and since I have it installed locally on my machines, I've never encountered the issue. I'll try to rectify this for the next version.
