### ISSUE TITLE
App crashes with segmentation fault

### ISSUE THREAD

**Issue by toaster** [arttuperala/kmbmpdc#3]
Hi there,

I tried to use kmbmpdc but as soon as I let it connect to my mpd server (requires password) it crashes. In terminal it just says: “Segmentation fault: 11”

I installed `libmpdclient` via Homebrew.

How can I provide additional information on this?
How can I help to solve this issue?

**Comment by arttuperala** [comment]
Can you build the `password-authentication` branch from source and test it?

**Comment by toaster** [comment]
I'll try … have to install Xcode first :).

**Comment by toaster** [comment]
It works!

Thank you. Now I can open the feature wishes :).
